services:
  mongo:
    image: mongo:7
    container_name: scv-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - scv-mongo-data:/data/db

volumes:
  scv-mongo-data:
